version: "3.8"
services:
  web:
    build: website
    ports:
      - 5000:5000
    environment:
      - DEBUG=1
    networks:
      - flask_network
    command: python main.py runserver 0.0.0.0:5000
